version: '3.7'

services:

  service-1:      
    build: ./service-1
    image: localhost:8082/service1
    container_name: service1
    ports: 
    - target: 5000
      published: 5000

  service-2:
    build: ./service-2
    image: localhost:8082/service2
    container_name: service2
    ports:
    - target: 5001
      published: 5001

  service-3:
    build: ./service-3
    image: localhost:8082/service3
    container_name: service3
    ports:
    - target: 5002
      published: 5002

  service-4:
    build: ./service-4
    image: localhost:8082/service4
    container_name: service4
    ports:
    - target: 5003
      published: 5003
