version: "3.7"

services:

  service1:
    image: service1 
    build:
      context: /home/student/QAProject/service-1/
      dockerfile: dockerfile_1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
      
  service2:
    image: service2
    build:
      context: /home/student/QAProject/service-2/
      dockerfile: dockerfile_2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
      
  service3:
    image: service3
    build:
      context: /home/student/QAProject/service-3/
      dockerfile: dockerfile_3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
      
  service4:
    image: service4
    build:
      context: /home/student/QAProject/service-4/
      dockerfile: dockerfile_4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
